// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Author: typeof import('./src/components/Author.vue')['default']
    BackLink: typeof import('./src/components/BackLink.tsx')['default']
    CommunityIcon: typeof import('./src/components/icons/CommunityIcon.vue')['default']
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    DocumentationIcon: typeof import('./src/components/icons/DocumentationIcon.vue')['default']
    EcosystemIcon: typeof import('./src/components/icons/EcosystemIcon.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    MetaTags: typeof import('./src/components/MetaTags.vue')['default']
    NavBarLinks: typeof import('./src/components/NavBarLinks.svelte')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PostDate: typeof import('./src/components/PostDate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportIcon: typeof import('./src/components/icons/SupportIcon.vue')['default']
    ToolingIcon: typeof import('./src/components/icons/ToolingIcon.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
